import baseColorUrl from '../assets/brick-wall.jpg';
import sourceUrl from '../assets/brick-source.jpg';

export const brickWallCard = {
  id: 'MAT-BRICK-0001',
  name: 'Weathered Tan Brick Wall',
  category: 'brick',
  subcategory: 'clay_masonry',
  description: 'Phone photograph of a weathered tan brick wall with visible mortar joints.',
  status: 'prototype',
  sourceType: 'user_photograph',
  sourceFiles: [
    { role: 'original', path: 'materials/brick/brick-wall-001/source/original-photo.jpg', url: sourceUrl },
    { role: 'crop', path: 'materials/brick/brick-wall-001/source/crop-source.jpg', url: baseColorUrl },
  ],
  license: 'CC0-1.0',
  provenance: {
    creator: 'user-provided photograph',
    collectionMethod: 'phone photograph',
    sourcePhoto: '9-Photo-9.jpg',
    licenseStatus: 'confirmed_by_user',
    note: 'The source is preserved under CC0-1.0 at the owner\'s direction; dimensions remain provisional.',
  },
  realWorldWidthMeters: 1,
  realWorldHeightMeters: 1,
  scaleStatus: 'unverified',
  pixelsPerMeter: 2048,
  defaultRepeat: [1, 1],
  mappingMethods: ['uv', 'planar', 'box', 'triplanar'],
  baseColorMap: 'materials/brick/brick-wall-001/maps/base-color.jpg',
  normalMap: null,
  roughnessMap: null,
  heightMap: null,
  aoMap: null,
  metalnessMap: null,
  opacityMap: null,
  roughness: 0.86,
  metalness: 0,
  normalStrength: 1,
  heightStrength: 0.12,
  displacementScale: 0,
  colorSpace: 'sRGB',
  seamless: false,
  tileabilityScore: 0.48,
  physicalScaleValidated: false,
  closeupValidated: false,
  curvedSurfaceValidated: false,
  verticalSurfaceValidated: false,
  antiTilingEnabled: false,
  variants: [],
  tags: ['brick', 'mortar', 'wall', 'weathered', 'prototype'],
  createdAt: '2026-08-01',
  updatedAt: '2026-08-01',
};

export const brickWallDefaults = {
  geometry: 'wall',
  lighting: 'neutral',
  camera: 'medium',
  channel: 'final',
  mapping: 'uv',
  sourceWidth: brickWallCard.realWorldWidthMeters,
  sourceHeight: brickWallCard.realWorldHeightMeters,
  repeatMultiplier: 1,
  roughness: brickWallCard.roughness,
  bumpStrength: brickWallCard.heightStrength,
  seams: true,
  scaleOverlay: true,
  antiTiling: false,
  quality: 'high',
  variant: 'base',
};
