import baseColorUrl from '../assets/sidewalk-concrete.jpg';
import sourceUrl from '../assets/sidewalk-source.jpg';

export const concretePebbleCard = {
  id: 'MAT-CONCRETE-0001',
  name: 'Concrete Pebble',
  category: 'concrete',
  subcategory: 'exposed_aggregate',
  description: 'Photographed sidewalk aggregate surface.',
  status: 'prototype',
  sourceType: 'user_photograph',
  sourceFiles: [
    { role: 'original', path: 'materials/concrete/concrete-pebble-001/source/original-photo.jpg', url: sourceUrl },
    { role: 'crop', path: 'materials/concrete/concrete-pebble-001/source/crop-source.jpg', url: baseColorUrl },
  ],
  license: 'CC0-1.0',
  provenance: {
    creator: 'user-provided photograph',
    collectionMethod: 'phone photograph',
    licenseStatus: 'confirmed_by_user',
    note: 'The owner has released this user-authored source under CC0-1.0; dimensions remain provisional.',
  },
  realWorldWidthMeters: 1,
  realWorldHeightMeters: 1,
  scaleStatus: 'unverified',
  pixelsPerMeter: 2048,
  defaultRepeat: [1, 1],
  mappingMethods: ['uv', 'planar', 'box', 'triplanar'],
  baseColorMap: 'materials/concrete/concrete-pebble-001/maps/base-color.jpg',
  normalMap: null,
  roughnessMap: null,
  heightMap: null,
  aoMap: null,
  metalnessMap: null,
  opacityMap: null,
  roughness: 0.94,
  metalness: 0,
  normalStrength: 1,
  heightStrength: 0.07,
  displacementScale: 0,
  colorSpace: 'sRGB',
  seamless: false,
  tileabilityScore: 0.22,
  physicalScaleValidated: false,
  closeupValidated: false,
  curvedSurfaceValidated: false,
  verticalSurfaceValidated: false,
  antiTilingEnabled: false,
  variants: [],
  tags: ['sidewalk', 'aggregate', 'concrete', 'prototype'],
  createdAt: '2026-08-01',
  updatedAt: '2026-08-01',
};

export const materialDefaults = {
  geometry: 'sidewalk',
  lighting: 'neutral',
  camera: 'medium',
  channel: 'final',
  mapping: 'uv',
  sourceWidth: concretePebbleCard.realWorldWidthMeters,
  sourceHeight: concretePebbleCard.realWorldHeightMeters,
  repeatMultiplier: 1,
  roughness: concretePebbleCard.roughness,
  bumpStrength: concretePebbleCard.heightStrength,
  seams: true,
  scaleOverlay: true,
  antiTiling: false,
  quality: 'high',
  variant: 'base',
};

export function materialCardForExport(state, card = concretePebbleCard) {
  return {
    ...card,
    sourceFiles: card.sourceFiles.map(({ path }) => path),
    realWorldWidthMeters: state.sourceWidth,
    realWorldHeightMeters: state.sourceHeight,
    updatedAt: new Date().toISOString(),
    runtimeOverrides: {
      geometry: state.geometry,
      lighting: state.lighting,
      camera: state.camera,
      channel: state.channel,
      mapping: state.mapping,
      repeatMultiplier: state.repeatMultiplier,
      roughness: state.roughness,
      bumpStrength: state.bumpStrength,
      antiTilingEnabled: state.antiTiling,
    },
  };
}
