import darkAsphaltImage from '../assets/dark-asphalt.jpg';
import darkAsphaltSource from '../assets/dark-asphalt-source.jpg';
import parkingAsphaltImage from '../assets/parking-lot-asphalt.jpg';
import parkingAsphaltSource from '../assets/parking-lot-asphalt-source.jpg';
import coarseAsphaltImage from '../assets/coarse-asphalt.jpg';
import coarseAsphaltSource from '../assets/coarse-asphalt-source.jpg';
import broadleafImage from '../assets/broadleaf.jpg';
import broadleafSource from '../assets/broadleaf-source.jpg';
import loopCarpetImage from '../assets/loop-carpet.jpg';
import loopCarpetSource from '../assets/loop-carpet-source.jpg';
import palePaversImage from '../assets/pale-pavers.jpg';
import palePaversSource from '../assets/pale-pavers-source.jpg';
import palePaversAlternateSource from '../assets/pale-pavers-alternate-source.jpg';
import crumpledTextileImage from '../assets/crumpled-gray-textile.jpg';
import crumpledTextileSource from '../assets/crumpled-gray-textile-source.jpg';

function createDefinition(config) {
  const sourceFiles = [
    { role: 'original', path: `${config.packagePath}/source/original-photo.jpg`, url: config.sourceUrl },
    ...(config.additionalSources ?? []).map((source) => ({
      role: source.role ?? 'alternate',
      path: `${config.packagePath}/source/${source.file}`,
      url: source.url,
    })),
    { role: 'crop', path: `${config.packagePath}/source/crop-source.jpg`, url: config.baseColorUrl },
  ];
  const card = {
    id: config.id,
    name: config.name,
    category: config.category,
    subcategory: config.subcategory,
    description: config.description,
    status: 'prototype',
    sourceType: 'user_photograph',
    sourceFiles,
    license: 'CC0-1.0',
    provenance: {
      creator: 'user-provided photograph',
      collectionMethod: 'phone photograph',
      sourcePhoto: config.sourcePhoto,
      sourcePhotos: config.sourcePhotos ?? [config.sourcePhoto],
      licenseStatus: 'confirmed_by_user',
      note: config.provenanceNote ?? 'Original source photographs are preserved. The owner has released this user-authored source under CC0-1.0.',
    },
    realWorldWidthMeters: 1,
    realWorldHeightMeters: 1,
    scaleStatus: 'unverified',
    pixelsPerMeter: 2048,
    defaultRepeat: [1, 1],
    mappingMethods: config.mappingMethods ?? ['uv', 'planar', 'box', 'triplanar'],
    baseColorMap: `${config.packagePath}/maps/base-color.jpg`,
    normalMap: null,
    roughnessMap: null,
    heightMap: null,
    aoMap: null,
    metalnessMap: null,
    opacityMap: null,
    roughness: config.roughness,
    metalness: config.metalness ?? 0,
    normalStrength: 1,
    heightStrength: config.heightStrength,
    displacementScale: 0,
    colorSpace: 'sRGB',
    seamless: false,
    tileabilityScore: config.tileabilityScore,
    physicalScaleValidated: false,
    closeupValidated: false,
    curvedSurfaceValidated: false,
    verticalSurfaceValidated: false,
    antiTilingEnabled: false,
    variants: [],
    tags: [...config.tags, 'prototype', 'cc0'],
    createdAt: '2026-08-01',
    updatedAt: '2026-08-01',
  };

  return {
    key: config.key,
    name: config.name,
    card,
    baseColorUrl: config.baseColorUrl,
    sourceUrl: config.sourceUrl,
    defaults: {
      geometry: config.geometry,
      lighting: config.lighting,
      camera: 'medium',
      channel: 'final',
      mapping: 'uv',
      sourceWidth: 1,
      sourceHeight: 1,
      repeatMultiplier: 1,
      roughness: config.roughness,
      bumpStrength: config.heightStrength,
      seams: true,
      scaleOverlay: true,
      antiTiling: false,
      quality: 'high',
      variant: 'base',
    },
  };
}

export const urbanBatch002Materials = {
  'dark-asphalt': createDefinition({
    key: 'dark-asphalt',
    id: 'MAT-ASPHALT-0001',
    name: 'Dark Weathered Asphalt',
    category: 'asphalt',
    subcategory: 'weathered_road_surface',
    description: 'Dark gray weathered asphalt with fine aggregate, small cracks, and reflective wear.',
    sourcePhoto: '1-Photo-1.jpg',
    packagePath: 'materials/asphalt/dark-asphalt-001',
    baseColorUrl: darkAsphaltImage,
    sourceUrl: darkAsphaltSource,
    geometry: 'large-plane',
    lighting: 'sunlight',
    roughness: 0.88,
    heightStrength: 0.1,
    tileabilityScore: 0.32,
    tags: ['asphalt', 'road', 'aggregate', 'weathered'],
  }),
  'parking-lot-asphalt': createDefinition({
    key: 'parking-lot-asphalt',
    id: 'MAT-ASPHALT-0002',
    name: 'Parking Lot Asphalt',
    category: 'asphalt',
    subcategory: 'parking_lot_surface',
    description: 'Smoother dark parking-lot asphalt. The runtime crop removes the contextual painted line and vehicles while the original remains preserved.',
    sourcePhoto: '2-Photo-2.jpg',
    packagePath: 'materials/asphalt/parking-lot-asphalt-001',
    baseColorUrl: parkingAsphaltImage,
    sourceUrl: parkingAsphaltSource,
    geometry: 'large-plane',
    lighting: 'overcast',
    roughness: 0.84,
    heightStrength: 0.06,
    tileabilityScore: 0.36,
    tags: ['asphalt', 'parking-lot', 'road', 'fine-aggregate'],
  }),
  'coarse-asphalt': createDefinition({
    key: 'coarse-asphalt',
    id: 'MAT-ASPHALT-0003',
    name: 'Coarse Asphalt Aggregate',
    category: 'asphalt',
    subcategory: 'coarse_aggregate_closeup',
    description: 'Close-up coarse asphalt aggregate with pronounced relief and a small retained piece of organic debris.',
    sourcePhoto: '3-Photo-3.jpg',
    packagePath: 'materials/asphalt/coarse-asphalt-001',
    baseColorUrl: coarseAsphaltImage,
    sourceUrl: coarseAsphaltSource,
    geometry: 'large-plane',
    lighting: 'grazing',
    roughness: 0.9,
    heightStrength: 0.14,
    tileabilityScore: 0.18,
    tags: ['asphalt', 'aggregate', 'macro', 'road'],
    provenanceNote: 'Original source is preserved. The crop retains a small piece of organic debris because it is part of the photographed environment; use the card as a macro reference until a cleaner crop is authored.',
  }),
  broadleaf: createDefinition({
    key: 'broadleaf',
    id: 'MAT-VEGETATION-0001',
    name: 'Silver-Green Broadleaf',
    category: 'vegetation',
    subcategory: 'broadleaf_surface',
    description: 'Silver-green broadleaf surface with visible veins. The crop is an organic reference, not an alpha-cutout leaf atlas.',
    sourcePhoto: '4-Photo-4.jpg',
    packagePath: 'materials/vegetation/broadleaf-001',
    baseColorUrl: broadleafImage,
    sourceUrl: broadleafSource,
    geometry: 'wall',
    lighting: 'overcast',
    roughness: 0.78,
    heightStrength: 0.04,
    tileabilityScore: 0.14,
    mappingMethods: ['uv', 'planar', 'world', 'triplanar'],
    tags: ['vegetation', 'leaf', 'broadleaf', 'organic'],
    provenanceNote: 'Original foliage context is preserved. The runtime crop emphasizes one broad leaf but retains neighboring leaf edges; use as a surface study until a cutout/opacity workflow is added.',
  }),
  'loop-carpet': createDefinition({
    key: 'loop-carpet',
    id: 'MAT-FABRIC-0001',
    name: 'Gray Loop Carpet',
    category: 'fabric',
    subcategory: 'loop_pile_carpet',
    description: 'Gray loop-pile carpet with dense directional fiber variation and soft micro-relief.',
    sourcePhoto: '5-Photo-5.jpg',
    packagePath: 'materials/fabric/loop-carpet-001',
    baseColorUrl: loopCarpetImage,
    sourceUrl: loopCarpetSource,
    geometry: 'large-plane',
    lighting: 'grazing',
    roughness: 0.98,
    heightStrength: 0.08,
    tileabilityScore: 0.46,
    tags: ['fabric', 'carpet', 'fiber', 'interior'],
  }),
  'pale-pavers': createDefinition({
    key: 'pale-pavers',
    id: 'MAT-STONE-0001',
    name: 'Pale Weathered Pavers',
    category: 'stone',
    subcategory: 'weathered_paver_grid',
    description: 'Pale gray stone or concrete paver field with cloudy mineral variation and dark joints.',
    sourcePhoto: '6-Photo-6.jpg',
    sourcePhotos: ['6-Photo-6.jpg', '7-Photo-6.jpg'],
    packagePath: 'materials/stone/pale-pavers-001',
    baseColorUrl: palePaversImage,
    sourceUrl: palePaversSource,
    additionalSources: [{ role: 'alternate', file: 'alternate-photo.jpg', url: palePaversAlternateSource }],
    geometry: 'large-plane',
    lighting: 'overcast',
    roughness: 0.82,
    heightStrength: 0.08,
    tileabilityScore: 0.34,
    tags: ['stone', 'pavers', 'mineral', 'joints'],
  }),
  'crumpled-gray-textile': createDefinition({
    key: 'crumpled-gray-textile',
    id: 'MAT-FABRIC-0002',
    name: 'Crumpled Gray Textile',
    category: 'fabric',
    subcategory: 'wrinkled_textile',
    description: 'Soft gray folded textile with broad wrinkles. The surrounding bench and carpet are excluded from the runtime crop.',
    sourcePhoto: '8-Photo-8.jpg',
    packagePath: 'materials/fabric/crumpled-gray-textile-001',
    baseColorUrl: crumpledTextileImage,
    sourceUrl: crumpledTextileSource,
    geometry: 'wall',
    lighting: 'grazing',
    roughness: 0.92,
    heightStrength: 0.2,
    tileabilityScore: 0.08,
    tags: ['fabric', 'textile', 'wrinkles', 'cloth'],
    provenanceNote: 'Original source is preserved. The crop removes most bench and carpet context, but the photographed folds are macro shape rather than a seamless micro texture.',
  }),
};
