import concreteSlabImage from '../assets/concrete-slab.jpg';
import concreteSlabSource from '../assets/concrete-slab-source.jpg';
import mixedRockSoilImage from '../assets/mixed-rock-soil.jpg';
import mixedRockSoilSource from '../assets/mixed-rock-soil-source.jpg';
import concretePaversAImage from '../assets/concrete-pavers-a.jpg';
import concretePaversASource from '../assets/concrete-pavers-a-source.jpg';
import concretePaversBImage from '../assets/concrete-pavers-b.jpg';
import concretePaversBSource from '../assets/concrete-pavers-b-source.jpg';
import lichenBarkImage from '../assets/lichen-bark.jpg';
import lichenBarkSource from '../assets/lichen-bark-source.jpg';
import scoredConcreteImage from '../assets/scored-concrete-pavers.jpg';
import scoredConcreteSource from '../assets/scored-concrete-pavers-source.jpg';
import redBrickPaversImage from '../assets/red-brick-pavers.jpg';
import redBrickPaversSource from '../assets/red-brick-pavers-source.jpg';
import roughBrickPaversImage from '../assets/rough-brick-pavers.jpg';
import roughBrickPaversSource from '../assets/rough-brick-pavers-source.jpg';

function createDefinition(config) {
  const card = {
    id: config.id,
    name: config.name,
    category: config.category,
    subcategory: config.subcategory,
    description: config.description,
    status: 'prototype',
    sourceType: 'user_photograph',
    sourceFiles: [
      { role: 'original', path: `${config.packagePath}/source/original-photo.jpg`, url: config.sourceUrl },
      { role: 'crop', path: `${config.packagePath}/source/crop-source.jpg`, url: config.baseColorUrl },
    ],
    license: 'provisional_user_authored',
    provenance: {
      creator: 'user-provided photograph',
      collectionMethod: 'phone photograph',
      sourcePhoto: config.sourcePhoto,
      licenseStatus: 'pending_user_confirmation',
      note: 'The source is preserved, but public asset licensing is not yet confirmed.',
    },
    realWorldWidthMeters: 1,
    realWorldHeightMeters: 1,
    scaleStatus: 'unverified',
    pixelsPerMeter: 2048,
    defaultRepeat: [1, 1],
    mappingMethods: ['uv', 'planar', 'box', 'triplanar'],
    baseColorMap: `${config.packagePath}/maps/base-color.jpg`,
    normalMap: null,
    roughnessMap: null,
    heightMap: null,
    aoMap: null,
    metalnessMap: null,
    opacityMap: null,
    roughness: config.roughness,
    metalness: 0,
    normalStrength: 1,
    heightStrength: config.heightStrength,
    displacementScale: 0,
    colorSpace: 'sRGB',
    seamless: false,
    tileabilityScore: config.tileabilityScore,
    physicalScaleValidated: false,
    closeupValidated: false,
    curvedSurfaceValidated: false,
    verticalSurfaceValidated: false,
    antiTilingEnabled: false,
    variants: [],
    tags: [...config.tags, 'prototype'],
    createdAt: '2026-08-01',
    updatedAt: '2026-08-01',
  };

  return {
    key: config.key,
    name: config.name,
    card,
    baseColorUrl: config.baseColorUrl,
    sourceUrl: config.sourceUrl,
    defaults: {
      geometry: config.geometry,
      lighting: config.lighting,
      camera: 'medium',
      channel: 'final',
      mapping: 'uv',
      sourceWidth: 1,
      sourceHeight: 1,
      repeatMultiplier: 1,
      roughness: config.roughness,
      bumpStrength: config.heightStrength,
      seams: true,
      scaleOverlay: true,
      antiTiling: false,
      quality: 'high',
      variant: 'base',
    },
  };
}

export const urbanBatchMaterials = {
  'concrete-slab': createDefinition({
    key: 'concrete-slab',
    id: 'MAT-CONCRETE-0002',
    name: 'Fine Concrete Slab',
    category: 'concrete',
    subcategory: 'fine_broomed_slab',
    description: 'Warm gray fine-aggregate concrete slab photographed outdoors.',
    sourcePhoto: '1-Photo-1.jpg',
    packagePath: 'materials/concrete/concrete-slab-002',
    baseColorUrl: concreteSlabImage,
    sourceUrl: concreteSlabSource,
    geometry: 'sidewalk',
    lighting: 'sunlight',
    roughness: 0.91,
    heightStrength: 0.06,
    tileabilityScore: 0.42,
    tags: ['concrete', 'slab', 'fine-aggregate'],
  }),
  'rock-soil': createDefinition({
    key: 'rock-soil',
    id: 'MAT-ROCK-0001',
    name: 'Mixed Rock Soil Ground',
    category: 'rock',
    subcategory: 'mixed_rock_soil',
    description: 'Mixed rounded and broken rock in dark soil with small organic debris.',
    sourcePhoto: '3-Photo-3.jpg',
    packagePath: 'materials/rock/mixed-rock-soil-001',
    baseColorUrl: mixedRockSoilImage,
    sourceUrl: mixedRockSoilSource,
    geometry: 'large-plane',
    lighting: 'overcast',
    roughness: 0.96,
    heightStrength: 0.18,
    tileabilityScore: 0.18,
    tags: ['rock', 'soil', 'gravel', 'ground-variation'],
  }),
  'concrete-pavers-a': createDefinition({
    key: 'concrete-pavers-a',
    id: 'MAT-CONCRETE-0003',
    name: 'Concrete Pavers A',
    category: 'concrete',
    subcategory: 'paver_grid',
    description: 'Gray and warm concrete pavers with dark joints and subtle surface wear.',
    sourcePhoto: '4-Photo-4.jpg',
    packagePath: 'materials/concrete/concrete-pavers-a-001',
    baseColorUrl: concretePaversAImage,
    sourceUrl: concretePaversASource,
    geometry: 'large-plane',
    lighting: 'neutral',
    roughness: 0.9,
    heightStrength: 0.08,
    tileabilityScore: 0.3,
    tags: ['concrete', 'pavers', 'joints', 'masonry'],
  }),
  'concrete-pavers-b': createDefinition({
    key: 'concrete-pavers-b',
    id: 'MAT-CONCRETE-0004',
    name: 'Concrete Pavers B',
    category: 'concrete',
    subcategory: 'weathered_paver_grid',
    description: 'Weathered concrete pavers with fine grain, dark joints, and warm tonal variation.',
    sourcePhoto: '5-Photo-5.jpg',
    packagePath: 'materials/concrete/concrete-pavers-b-001',
    baseColorUrl: concretePaversBImage,
    sourceUrl: concretePaversBSource,
    geometry: 'large-plane',
    lighting: 'overcast',
    roughness: 0.88,
    heightStrength: 0.08,
    tileabilityScore: 0.28,
    tags: ['concrete', 'pavers', 'weathered', 'joints'],
  }),
  bark: createDefinition({
    key: 'bark',
    id: 'MAT-BARK-0001',
    name: 'Lichen Bark',
    category: 'bark',
    subcategory: 'lichen_covered_bark',
    description: 'Rough tree bark with bright lichen, retained depth-of-field, and organic variation.',
    sourcePhoto: '6-Photo-6.jpg',
    packagePath: 'materials/bark/lichen-bark-001',
    baseColorUrl: lichenBarkImage,
    sourceUrl: lichenBarkSource,
    geometry: 'cylinder',
    lighting: 'grazing',
    roughness: 0.9,
    heightStrength: 0.2,
    tileabilityScore: 0.12,
    tags: ['bark', 'lichen', 'organic', 'mossy'],
  }),
  'scored-concrete': createDefinition({
    key: 'scored-concrete',
    id: 'MAT-CONCRETE-0005',
    name: 'Scored Concrete Pavers',
    category: 'concrete',
    subcategory: 'scored_paver_grid',
    description: 'Light scored concrete pavers with repeated grid joints and fine linear tooling.',
    sourcePhoto: '7-Photo-7.jpg',
    packagePath: 'materials/concrete/scored-concrete-001',
    baseColorUrl: scoredConcreteImage,
    sourceUrl: scoredConcreteSource,
    geometry: 'large-plane',
    lighting: 'neutral',
    roughness: 0.9,
    heightStrength: 0.08,
    tileabilityScore: 0.36,
    tags: ['concrete', 'pavers', 'scored', 'grid'],
  }),
  'red-brick-pavers': createDefinition({
    key: 'red-brick-pavers',
    id: 'MAT-BRICK-0002',
    name: 'Red Brick Pavers',
    category: 'brick',
    subcategory: 'red_paver_grid',
    description: 'Red and brown brick pavers with dark joints, wear, and strong sun variation.',
    sourcePhoto: '8-Photo-8.jpg',
    packagePath: 'materials/brick/red-brick-pavers-001',
    baseColorUrl: redBrickPaversImage,
    sourceUrl: redBrickPaversSource,
    geometry: 'large-plane',
    lighting: 'sunlight',
    roughness: 0.84,
    heightStrength: 0.1,
    tileabilityScore: 0.26,
    tags: ['brick', 'pavers', 'red-brick', 'joints'],
  }),
  'rough-brick-pavers': createDefinition({
    key: 'rough-brick-pavers',
    id: 'MAT-BRICK-0003',
    name: 'Rough Tan Brick Pavers',
    category: 'brick',
    subcategory: 'rough_masonry_paver',
    description: 'Rough tan brick or masonry pavers separated by dark aggregate joints.',
    sourcePhoto: '10-Photo-10.jpg',
    packagePath: 'materials/brick/rough-brick-pavers-001',
    baseColorUrl: roughBrickPaversImage,
    sourceUrl: roughBrickPaversSource,
    geometry: 'large-plane',
    lighting: 'grazing',
    roughness: 0.88,
    heightStrength: 0.16,
    tileabilityScore: 0.22,
    tags: ['brick', 'masonry', 'rough', 'pavers'],
  }),
};
