import baseColorUrl from '../assets/wood-weathered.jpg';
import sourceUrl from '../assets/wood-source.jpg';

export const weatheredWoodCard = {
  id: 'MAT-WOOD-0001',
  name: 'Weathered Wood Pole',
  category: 'wood',
  subcategory: 'weathered_softwood',
  description: 'Phone photograph of vertically grained, weathered wood with gray sun damage and warm exposed timber.',
  status: 'prototype',
  sourceType: 'user_photograph',
  sourceFiles: [
    { role: 'original', path: 'materials/wood/weathered-pole-001/source/original-photo.jpg', url: sourceUrl },
    { role: 'crop', path: 'materials/wood/weathered-pole-001/source/crop-source.jpg', url: baseColorUrl },
  ],
  license: 'CC0-1.0',
  provenance: {
    creator: 'user-provided photograph',
    collectionMethod: 'phone photograph',
    sourcePhoto: '2-Photo-2.jpg',
    licenseStatus: 'confirmed_by_user',
    note: 'The source is preserved under CC0-1.0 at the owner\'s direction; dimensions remain provisional.',
  },
  realWorldWidthMeters: 1,
  realWorldHeightMeters: 1,
  scaleStatus: 'unverified',
  pixelsPerMeter: 2048,
  defaultRepeat: [1, 1],
  mappingMethods: ['uv', 'planar', 'box', 'triplanar'],
  baseColorMap: 'materials/wood/weathered-pole-001/maps/base-color.jpg',
  normalMap: null,
  roughnessMap: null,
  heightMap: null,
  aoMap: null,
  metalnessMap: null,
  opacityMap: null,
  roughness: 0.82,
  metalness: 0,
  normalStrength: 1,
  heightStrength: 0.14,
  displacementScale: 0,
  colorSpace: 'sRGB',
  seamless: false,
  tileabilityScore: 0.35,
  physicalScaleValidated: false,
  closeupValidated: false,
  curvedSurfaceValidated: false,
  verticalSurfaceValidated: false,
  antiTilingEnabled: false,
  variants: [],
  tags: ['wood', 'weathered', 'vertical-grain', 'pole', 'prototype'],
  createdAt: '2026-08-01',
  updatedAt: '2026-08-01',
};

export const weatheredWoodDefaults = {
  geometry: 'cylinder',
  lighting: 'grazing',
  camera: 'medium',
  channel: 'final',
  mapping: 'uv',
  sourceWidth: weatheredWoodCard.realWorldWidthMeters,
  sourceHeight: weatheredWoodCard.realWorldHeightMeters,
  repeatMultiplier: 1,
  roughness: weatheredWoodCard.roughness,
  bumpStrength: weatheredWoodCard.heightStrength,
  seams: true,
  scaleOverlay: true,
  antiTiling: false,
  quality: 'high',
  variant: 'base',
};
